site_name: SigCecp
site_url: https://github.com/mdsreq-fga-unb/REQ-2026.2-T01-SigCecp

nav: 
  - Home: index.md
  - Visão de produto e projeto:
    - Cenario atual: visao_produto_projeto/1_cenario_atual.md
    - Solução Proposta: visao_produto_projeto/2_solucao_proposta.md
    - Intervenção social: visao_produto_projeto/3_intervencao_social.md
    - Estrategias de ESW: visao_produto_projeto/4_estrategias_esw.md
    - Engenharia de Requisitos: visao_produto_projeto/5_engenharia_req.md
    - Cronograma e entrega: visao_produto_projeto/6_cronograma.md
    - Interação entre a equipe e o cliente: visao_produto_projeto/7_interacao_equipe_e_cliente.md
    - Requisitos: visao_produto_projeto/8_0_requisitos.md
    - Lições Aprendidas: visao_produto_projeto/11_licoes_aprendidas.md
  - Gravações:
    - Apresentações das Unidades:
      - Unidade 1: gravacoes/apresentacoes_unidades/apresentacao_unidade_1.md
    - Reuniões:
      - Cliente:
        - Reunião 17/09/2026: gravacoes/reunioes_cliente/reuniao_audio_17_09.md
        - Reunião 22/09/2026: gravacoes/reunioes_cliente/reuniao_audio_22_09.md
        - Reunião 24/09/2026: gravacoes/reunioes_cliente/reuniao_audio_24_09.md
        - Reunião 26/09/2026: gravacoes/reunioes_cliente/reuniao_audio_26_09.md
      - Equipe:
        - Reunião 28/08/2026: gravacoes/reunioes_equipe/reuniao_video_28_08.md
        - Reunião 04/09/2026: gravacoes/reunioes_equipe/reuniao_video_04_09.md
        - Reunião 24/09/2026: gravacoes/reunioes_equipe/reuniao_video_24_09.md
        - Reunião MoSCoW 26/09/2026: gravacoes/reunioes_equipe/reuniao_video_26_09.md
  - Organizacao e Planejamento:
    - Atas de Reuniões:
      - Cliente:
        - Reunião dia 17/09/2026: organizacao_e_planejamento/atas_reunioes/cliente/ata_reuniao_17_09.md
        - Reunião dia 22/09/2026: organizacao_e_planejamento/atas_reunioes/cliente/ata_reuniao_22_09.md
        - Reunião dia 24/09/2026: organizacao_e_planejamento/atas_reunioes/cliente/ata_reuniao_24_09.md
        - Reunião dia 26/09/2026: organizacao_e_planejamento/atas_reunioes/cliente/ata_reuniao_26_09.md
      - Equipe:
        - Reunião dia 28/08/2026: organizacao_e_planejamento/atas_reunioes/equipe/ata_reuniao_28_08.md
        - Reunião dia 04/09/2026: organizacao_e_planejamento/atas_reunioes/equipe/ata_reuniao_04_09.md
        - Reunião dia 26/09/2026: organizacao_e_planejamento/atas_reunioes/equipe/ata_reuniao_26_09.md

    - Ajustes e validações: organizacao_e_planejamento/ajuste_e_validacao.md

theme:
  name: material
  palette:
    - scheme: default
      primary: black
      accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      toc_depth: "2-4"
  - pymdownx.snippets:
      base_path: ["docs"]

extra_css:
  - stylesheets/extra.css
